name: 'Quick check'
description: 'Check and lint'

inputs:
  git-credencials:
    description: 'Git credencials'
    required: true
  buf-token:
    description: 'Buf token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure git credentials
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: |
          ${{ inputs.git-credencials }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set-up cargo configuration
      shell: bash
      run: |
        if [ -e "ci-cargo-config.toml" ]; then
          install -D "ci-cargo-config.toml" "$HOME/.cargo/config.toml"
        fi

    # TODO: Use a well-defined version
    - name: Update local toolchain
      shell: bash
      run: |
        rustup update
        sudo apt-get update

    - name: Install buf
      shell: bash
      run: |
        curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.38.0/buf-$(uname -s)-$(uname -m)" -o "/usr/local/bin/buf"
        chmod +x "/usr/local/bin/buf"

    - name: Format
      shell: bash
      env:
        BUF_TOKEN: "${{ inputs.BUF_TOKEN }}"
      run: cargo fmt --check 

    - name: Clippy
      shell: bash
      env:
        BUF_TOKEN: "${{ inputs.BUF_TOKEN }}"
      run: |
        cargo clippy -- -D warnings 
