name: 'Quick check'
description: 'Check and lint'

env:
  CARGO_TERM_COLOR: always

inputs:
  git-credencials:
    description: 'Git credencials'
    required: true
  buf-token:
    description: 'Buf token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure git credentials
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: |
          ${{ inputs.git-credencials }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set-up cargo configuration
      shell: bash
      run: |
        if [ -e "ci-cargo-config.toml" ]; then
          install -D "ci-cargo-config.toml" "$HOME/.cargo/config.toml"
        fi

    - name: Format
      env:
        BUF_TOKEN: "${{ inputs.BUF_TOKEN }}"
      uses: proton-decay/github-ci-action/tools@main 
      with:
        command: cargo fmt --check

    - name: Clippy
      env:
        BUF_TOKEN: "${{ inputs.BUF_TOKEN }}"
      uses: proton-decay/github-ci-action/tools@main 
      with:
        command: cargo clippy -- -D warnings 
